sdemarre/diophantine/README.md
image links in readme were wrong
=> fix image link

sdemarre/diophantine/diophantine.asd, sdemarre/diophantine/diophantine_devel.mac
diophantine_devel.mac now has a note that it is not part of the actual
solver.
got rid of some functions of which I couldn't find remember what they
are used for and were no longer working.
=> asdf no longer uses diophantine_devel

robert-dodier/diff_sum/rtest_diff_sum.mac, robert-dodier/sum_kron_delta/rtest_sum_kron.mac, robert-dodier/sum_kron_delta/sum_kron_delta.mac
Update sum_kron_delta and diff_sum packages following commit 801a0bb (tellsimpafter modification) on maxima.
=> Post-commit-801a0bb update

yitzchak/texify/LICENSE.md, yitzchak/texify/README.md, yitzchak/texify/texify.asd, yitzchak/texify/texify.lisp
There is still a lot of work to do and only minimal documentation in the README, but everything appears working enough for others to take it for a spin.
=> Add texify package

yitzchak/texify/CHANGELOG.md, yitzchak/texify/LICENSE.md, yitzchak/texify/README.md, yitzchak/texify/texify.lisp
This PR includes some updates from feedback received via `maxima-discuss` plus some bug fixes.
=> Updates to texify from initial feedback

robert-dodier/lexical_symbols/lexical_symbols.lisp
Additional work on lexical symbols stuff. In particular now lexical symbols are introduced by the parser.
=> Additional work on lexical symbols

robert-dodier/lexical_symbols/find_dynamic_binding.mac, robert-dodier/lexical_symbols/lexical_symbols.lisp, robert-dodier/lexical_symbols/rtest_lexical_symbols.mac, robert-dodier/subst_floats/subst_floats.mac
A lot of work on lexical symbols and a new function (in a different subproject) named subst_floats.
=> Work on lexical symbols and new function subst_floats

robert-dodier/diff_sum/rtest_diff_sum.mac
Also, make local declarations that diff and sum are linear instead of global.
=> In tests for diff_sum, new tests for diff wrt specific index.

robert-dodier/lexical_symbols/rtest_lexical_symbols.mac, robert-dodier/lexical_symbols/with-lexical-environment.lisp
Initial implementation of lexical environments via hash tables which store (symbol, value) pairs.
=> Initial implementation of lexical environments

robert-dodier/lexical_symbols/mlambda.lisp, robert-dodier/lexical_symbols/with-lexical-environment.lisp
Several minor changes, experimenting with some ideas. Probably not in a consistently working state. Work in progress, more to come in near future.
=> Dodier lexical symbols update 2020 feb

robert-dodier/lexical_symbols/mlambda.lisp, robert-dodier/lexical_symbols/with-lexical-environment.lisp
Many changes in various places, I think I have a more or less working implementation of closures, or at least enough for experimentation.
=> many updates, closures more or less working now

robert-dodier/complex_plots/README.md, robert-dodier/complex_plots/complex_plot_2d.template, robert-dodier/complex_plots/complex_plot_3d.template, robert-dodier/complex_plots/complex_plots.mac, robert-dodier/complex_plots/slurp.lisp, robert-dodier/lexical_symbols/lexical_symbols.lisp, robert-dodier/lexical_symbols/rtest_lexical_symbols.mac
Merge complex_plots and also some changes to lexical_symbols
=> Merge complex_plots and also some changes to lexical_symbols

robert-dodier/lexical_symbols/lexical_symbols.demo, robert-dodier/lexical_symbols/lexical_symbols.mac, robert-dodier/lexical_symbols/rtest_lexical_symbols.mac, robert-dodier/lexical_symbols/with-lexical-environment.lisp, robert-dodier/tex_table/tex_table.mac
Fixing some problems and additional test cases in lexical_symbols.
Float formatting in tex_table.
=> Merge recent updates from my branch

robert-dodier/excel_round/excel_round.mac, robert-dodier/excel_round/rtest_excel_round.mac, robert-dodier/lexical_symbols/mset.lisp
new package excel_round; intercept assignments in lexical symbols
=> new package excel_round; intercept assignments in lexical symbols

robert-dodier/fboundp/fboundp.mac, robert-dodier/fboundp/rtest_fboundp.mac
New function fboundp to detect different kinds of functions.
=> New function fboundp to detect different kinds of functions.

bertrand-teguia/Hypergeometric-Term-Holonomic-REs/HyperTermHoloRE.mac
1- Use properties of solutions involving algebraic numbers
2- A new function 'removeConst' to clear the outputs of multiplicative constants
=> Updates in HyperTermHoloRE.mac

robert-dodier/lexical_symbols/find_dynamic_binding.mac, robert-dodier/lexical_symbols/lexical_symbols.lisp, robert-dodier/lexical_symbols/plan6.txt, robert-dodier/lexical_symbols/rtest_lexical_symbols.mac, robert-dodier/lexical_symbols/rtest_lexical_symbols_only.mac
Various updates for package lexical_symbols, in particular for lexical_symbols.lisp and rtest_lexical_symbols_only.mac.
Also create a plan for merging lexical_symbols into a would-be Maxima 6 release in some way.
=> Various updates for lexical_symbols

robert-dodier/lexical_symbols/meval.lisp, robert-dodier/lexical_symbols/plan6.txt
Commit modified MEVAL which binds lexical variables when evaluating a closure and then punts to built-in MEVAL.
=> Commit modified MEVAL which binds lexical variables

robert-dodier/simplify_conditionals/rtest_simplify_conditionals.mac, robert-dodier/simplify_conditionals/simplify_conditionals.mac
New package simplify_conditionals, containing two functions: `flatten_conditionals` to flatten nested conditionals, and `arithmetic_with_conditionals` to apply `+` and `*` to conditionals.
=> New package simplify_conditionals

robert-dodier/lexical_symbols/rtest_lexical_symbols_only.mac
Additional test cases for lexical symbols.
=> Additional test cases

robert-dodier/lexical_symbols/mlambda.lisp, robert-dodier/lexical_symbols/rtest_lexical_symbols.mac, robert-dodier/lexical_symbols/rtest_lexical_symbols_only.mac, robert-dodier/lexical_symbols/simplify_product.mac, robert-dodier/lexical_symbols/with-lexical-environment.lisp
Some minor updates from my personal fork.
=> Merge recent work into base repo

robert-dodier/lexical_symbols/rtest_lexical_symbols_only.mac, robert-dodier/qmpe/qmpe.demo, robert-dodier/qmpe/qmpe.mac, robert-dodier/qmpe/rtest_qmpe.mac
New package qmpe (quantile maximum probability estimates), and also a test case for lexical_symbols.
=> New package qmpe (quantile maximum probability estimates)

robert-dodier/expm/expm.mac, robert-dodier/from_wxmx/README.md, robert-dodier/from_wxmx/expressions_from_dom.lisp, robert-dodier/from_wxmx/expressions_from_dom.mac, robert-dodier/from_wxmx/expressions_from_xml.lisp, robert-dodier/from_wxmx/from_wxmx.mac, robert-dodier/lexical_symbols/rtest_lexical_symbols_only.mac, robert-dodier/random_expression/random_expression.mac
Merge recent work from personal fork.
* matrix exponential via Pade approximation
* substantially revised from_wxmx, including new capability to read .wxmx zip file via CL library zippy
* a test case for lexical symbols
* function to generate random expressions
=> Merge recent work from fork: matrix exponential, revised from_wxmx, a few other changes

robert-dodier/reshape/index-reshape.lisp, robert-dodier/reshape/reshape.info, robert-dodier/reshape/reshape.texi
Put examples into documentation and generate info and index files.
=> Put examples into documentation and generate info and index files

robert-dodier/diff_sum/diff_sum.mac, robert-dodier/diff_sum/diff_sum2.mac, robert-dodier/diff_sum/rtest_diff_sum.mac, robert-dodier/from_wxmx/from_wxmx.mac, robert-dodier/lexical_symbols/rtest_lexical_symbols_only.mac
merge recent changes in from_wxmx, lexical_symbols, and diff_sum
=> merge recent changes in from_wxmx, lexical_symbols, and diff_sum

robert-dodier/lexical_symbols/rtest_lexical_symbols.mac, robert-dodier/lexical_symbols/rtest_lexical_symbols_only.mac
* rtest_lexical_symbols.mac: fix up expected results and create new test cases
* rtest_lexical_symbols_only.mac: create new test cases
=> Package lexical_symbols: revision and expansion of test scripts.

robert-dodier/combining_diacritics/README.md, robert-dodier/combining_diacritics/combining_diacritics.lisp, robert-dodier/plottable_steps/plottable_steps.mac, yitzchak/texify/nregex.lisp, yitzchak/texify/texify.lisp
merge recent changes for plottable_steps, combining_diacritics, and texify.
=> merge recent changes: plottable_steps, combining_diacritics, and texify

robert-dodier/distribute_over_tranches/distribute_over_tranches.lisp, robert-dodier/distribute_over_tranches/rtest_distribute_over_tranches.mac, robert-dodier/distribute_over_tranches/tick_tock.mac
new package distribute_over_tranches
=> new package distribute_over_tranches
